# Permalinks
permalink:           pretty

# Setup
title:               Swift 小专栏
url:                 http://swiftxiaozhuanlan.com
paginate:            10
baseurl:             ""
analytics_id:        UA-166630917-1

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              zhao
  url:               https://twitter.com/papazhao
  email:             15431230@qq.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/PaPazhao/PaPaZhao.github.io

# Gems
plugins:
  - jekyll-avatar
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
