# Basic
title: 秘密基地
subtitle: 欢迎来到秘密基地
welcome_message: <a href="" target="_blank">开始旅程</a>
description: Vno Jekyll is a port of my Ghost theme vno.
creator: <a href="http://www.baidu.com">@onevcat</a>

url: "http://www.sino.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: navy

# The blog button should not be removed.
blog_button:
    title: 主页
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://wwww.blank.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    # weibo: onevcat
    github: PaPaZhao
    # twitter: onevcat
    # gplus: 107108267983477358170
    mail: lizhao15431230@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
